import React, { useState } from "react"
import {Header} from "./Header/Header"
import {Footer} from "./Footer/Footer"
import {Breadcrumb} from "../Elements/Breadcrumb"

const Layout = () => {
    const [isToggled, setToggled] = useState(false);
    const toggleClick = () => {
        setToggled(!isToggled);
    };

    return (
        <>
            <head>
                <title>Nest - Redux NextJS eCommerce Template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>

            {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>}

            <Header />
            {/*<MobileMenu isToggled={isToggled} toggleClick={toggleClick} />*/}
            <main className="main">
                <Breadcrumb />
            </main>
            <Footer />
        </>
    );
};

export default Layout;
